name: Terraform Destroy

on:
  workflow_dispatch:

env:
  SWAN_AWS_REGION: "ap-southeast-1"
  TF_VAR_swan_ci_iam_role_arn: ${{ secrets.SWAN_CI_IAM_ROLE_ARN }}

permissions:
  id-token: write # id-token write permission is needed to use OIDC

jobs:
  swan_terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swan_terraform/swan_environments/swan_production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.SWAN_CI_IAM_ROLE_ARN }}
          aws-region: ${{ env.SWAN_AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var-file=prod.tfvars